config/routes.rb
Rails.application.routes.draw do

  resources :messages
  devise_for :users
  root to: "users#index"
  resources :users do
    member do
      post :friendships, to: 'friendships#create', as: 'new_friend'
      delete  :friendships, to: 'friendships#delete', as: 'delete_friend'
    end

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :from, class_name: 'User', foreign_key: 'from'
  belongs_to :to, class_name: 'User', foreign_key: 'to'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :send_messages, class_name: 'Message', foreign_key: :from
  has_many :received_messages, class_name: 'Message', foreign_key: :to

  validates :username, presence: true

  def messages
    Message.where('"from" = ? OR "to" = ?', id, id)
  end

  def friend_with?(user)
    friendship_with(user).any?
  end

  def friendship_with(user)
    Friendship.where("(creator_id = ? AND friend_id = ?) OR (creator_id = ? AND friend_id = ?)", id, user.id, user.id, id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    Friendship.create(creator_id: current_user.id, friend_id: params[:id])
    redirect_to :back
  end

  def delete
    user = User.find(params[:id])
    current_user.friendship_with(user).delete_all
    redirect_to :back
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = current_user.messages.page(params[:page])
  end

  def new
    @message = Message.new(from: current_user.id, to: params[:user_id])
  end

  def create
    message = Message.create(from: current_user.id, to: params[:message][:to], body: params[:message][:body])
    if message.persisted?
      redirect_to users_path, notice: 'Message sent!'
    else
      render 'new'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Simple Messaging</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li>
          <%- if user_signed_in? -%>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          <%- else -%>
              <%= link_to "Login", new_user_session_path %>
          <%- end -%>
        </li>
        <li><%= link_to 'Users', users_path %></li>
        <%- if user_signed_in? -%>
            <li><%= link_to 'Messages', messages_path %></li>
        <%- end -%>


      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>Simple Messaging</title>

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>

<%=render 'layouts/navigation' %>

<div class="container">

  <%- if notice -%>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <%- end -%>

  <%- if alert -%>
      <div class="alert alert-danger">
        <%= alert %>
      </div>
  <%- end -%>


  <%= yield %>
</div>



</body>
</html>

app/views/messages/_message.html.erb
<tr>
  <td>
    <%= message.from.username %>
  </td>

  <td>
    <%= message.to.username %>
  </td>

  <td>
    <%= message.body %>
  </td>
</tr>

app/views/messages/index.html.erb
<h1>Messages</h1>
<table class="table">
  <thead>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
    <%= render @messages %>
  </tbody>
</table>

<%= paginate @messages %>

app/views/messages/new.html.erb
<h1>Send a Message</h1>


<%= bootstrap_form_for(@message) do |f| %>
    <%= f.hidden_field :to %>
    <%= f.text_area :body %>

    <%= f.submit "Send" %>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.username %></td>
  <td><%= user.email%></td>
  <td>
    <%- if user_signed_in? %>
      <% if current_user.friend_with?(user) %>
        <%= link_to 'Remove from Friends', delete_friend_user_path(user), method: :delete, class: 'btn btn-danger' %>
        <%= link_to 'Send a Message', new_message_path(user_id: user.id), class: 'btn btn-success' %>
      <%- else -%>
            <%= link_to 'Add Friend', new_friend_user_path(user), method: :post, class: 'btn btn-primary' %>

      <% end %>
    <% end %>
  </td>
</tr>

app/views/users/index.html.erb
<h1>Users</h1>
<table class="table">
  <tbody>
    <%= render @users %>
  </tbody>

</table>

<%= paginate @users %>